title: Florian Martin-Bariteau
description: University Research Chair in Technology and Society, University of Ottawa. A technologist and creative turned legal scholar.

url: http://f-mb.org/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

url_home: /home/
url_home_fr: /accueil/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: About
   url: /biography/
 - title: Contact
   url: /contact/
 - title: "› French"
   url: /accueil/

navigation_fr:
 - title: À propos
   url: /biographie/
 - title: Contact
   url: /coordonnees/
 - title: "› English"
   url: /home/

social:
   twitter: f_mb
   email: fmb@uOttawa.ca

google_analytics: "UA-10030663-7"
