title: Florian Martin-Bariteau
description: LL.D. candidate and Lecturer, Université de Montréal. Global Internet Policy Fellow, Instituto de Tecnologia e Sociedade do Rio. A technologist and creative turned legal scholar.

url: http://f-mb.org/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: About
   url: /about/
 - title: Writings
   url: /writings/
 - title: Talks
   url: /talks/
 - title: Contact
   url: /contact/

social:
   twitter: f_mb
   email: florian@martinbariteau.org

google_analytics: "UA-10030663-7"
