title: Florian Martin-Bariteau
description: Assistant Professor and Director, Centre for Law, Technology and Society, University of Ottawa. A technologist and creative turned legal scholar.

url: http://f-mb.org/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: About
   url: /about/
 - title: Writings
   url: /writings/
 - title: Talks
   url: /talks/
 - title: Contact
   url: /contact/

navigation_fr:
 - title: À propos
   url: /a-propos/
 - title: Publications
   url: /publications/
 - title: Présentations
   url: /presentations/
 - title: Contact
   url: /coordonnees/

social:
   twitter: f_mb
   email: fmb@uOttawa.ca

google_analytics: "UA-10030663-7"
